# Site settings
title: Unirob
motto: I'm korean. Here is Unirob's shitty blog.
email: zkem70@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Hello. I'm Unirob! welcome to my shitty blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://unirob.ga" # the base hostname & protocol for your site
youtube_username: https://www.youtube.com/channel/UCWSMygIRyrcQDR6ivbJkp1w
github_username: github.com/Unirob79/Unirob79.github.io/

# Build settings
markdown: kramdown
permalink: /:title/
